### ISSUE TITLE
It is not an issue, just a suggestion

### ISSUE THREAD

**Issue by HZZformGD** [daybrush/moveable#1057]
I've been using this lib for a while, and I'm grateful to the author for his dedication. I found that the whole lib has a lot of Bravo features, and I want to say that these little features can also be separated into a library, for example, I think I like the functions of clipable, and I hope that you will also separate it @daybrush

**Comment by daybrush** [comment]
@HZZformGD 

It's a very good idea.

I want to separate it by the core.
MoveableManager is core and able is similar to plugin.

Some ables may feel unimportant to you.
So, instead of deleting it, I plan to separate it into another module.


Additionally, it is being separated and combined into several modules such as `gesto`, `@daybrush/utils`, and `css-to-matrix`.

**Comment by HZZformGD** [comment]
@daybrush , I expect it so much.  Clipale first plz , hah~  By the way , could you please check my previous issue.   [Issue1014](https://github.com/daybrush/moveable/issues/1014) Do you have any clue ?
