### ISSUE TITLE
When is moveable-avoid class applied?

### ISSUE THREAD

**Issue by adityakrshnn** [daybrush/moveable#130]
Hi, I wanted to know when moveable-avoid is applied? What does it do?

**Comment by daybrush** [comment]
@adityakrshnn 

It's for group or `dragArea: true`

Because dragArea wraps all the targets.

So we don't just wrap the points that are killed to know which target we clicked.
So we add the avoid class when dragStart.

red zone is `.moveable-area.moveable-avoid+.moveable-area-pieces`

![redzone](https://user-images.githubusercontent.com/3433062/71272219-e149d400-2396-11ea-8aab-75ee222dcd24.png)
