### ISSUE TITLE
[Feature request] Please add zoom support

### ISSUE THREAD

**Issue by ladifire** [daybrush/moveable#158]
Hi @daybrush 
Please add an option for using with zoom.
![captured (6)](https://user-images.githubusercontent.com/51266596/72417329-3d8ff000-37ab-11ea-9601-f6c2312ca184.gif)
The control points size should keep original size when zoom in/out
thank you!

**Comment by daybrush** [comment]
@ladifire 

* `moveable` 0.15.1
* `react-moveable` 0.18.0
* `preact-moveable` 0.17.0
* `ngx-moveable` 0.11.0
* `svelte-moveable` 0.6.0

Use `zoom` props

**Comment by Raphe-dev** [comment]
@daybrush 
The zoom update works like a charm, thank you no more needs to handle that manually!

But there is a problem ( I had that same problem with manual zoom management ) : The elementGuidelines and snap is not working properly when zoomed in/out, it only works properly when at 100% otherwise the lines / snap are off the actual element. 
I have been trying to fix that for a while but I am clueless on that issue.

**Comment by Samoji** [comment]
@Raphe-dev can you please give me an example of working code? I've done many tries but I can't make this work.
Thank you!
