### ISSUE TITLE
The button event can not be triggered

### ISSUE THREAD

**Issue by nzbin** [daybrush/moveable#543]
## Environments

* Framework name: null
* Framework version: null
* Moveable Component version: 0.26.0
* Testable Address(optional): https://codesandbox.io/s/moveable-jpwgh?file=/index.html

## Description

When upgrade moveable to latest version (`v0.26.0`), the button event can not be triggered.

https://codesandbox.io/s/moveable-jpwgh?file=/index.html

**Comment by sagrawal31** [comment]
Well, amazing. Today I was facing the same issue and I was trying to bang my head. Basically, when the `draggable = true`, I do not get the click event on the element. I hope this issue will solve that.

**Comment by daybrush** [comment]
@sagrawal31 

Test react-moveable@0.30.0-beta.0 (beta)

**Comment by sagrawal31** [comment]
Thanks for the test release. I realized later that this issue is for React apps while I'm using vanilla JS in my Angular app.

**Comment by sagrawal31** [comment]
Hi, @daybrush. As I have mentioned above, I'm actually facing the same issue with Vanilla JS (using 0.26.0). When the `draggable` is set to `true` on an element, any of its child nodes/elements are not receiving the click event.

While this problem does not exist if `draggable: false`. For example- when I try to click on that image in the screenshot, the click event is not received on the image element, and it only comes to the parent, i.e. selected element.

![image](https://user-images.githubusercontent.com/1804514/140409573-9e0a4e8d-6977-4175-889b-e8a301d1cd21.png)

For now, I have added this hack as a workaround to the problem-

![image](https://user-images.githubusercontent.com/1804514/140409411-f7a66121-c45b-44ea-8e2a-badfa80c6126.png)

Any thoughts? Maybe instead of fixing at React, some fix is required at the lower level?

**Comment by daybrush** [comment]
@sagrawal31 @nzbin 

* `moveable` 0.27.1
* `react-moveable` 0.30.1
* `preact-moveable` 0.29.1
* `ngx-moveable` 0.23.1
* `svelte-moveable` 0.18.1
* `lit-moveable` 0.4.1
* `vue-moveable` 2.0.0-beta.3
* `vue3-moveable` 0.2.1


moveable's new version is released. Check it again.

**Comment by sagrawal31** [comment]
@daybrush, I just tested the release 0.27.1, and the problem is gone 🤩  Thanks a ton!
