### ISSUE TITLE
Zoomed / big cursor pointers in Firefox

### ISSUE THREAD

**Issue by adilmas13** [daybrush/moveable#589]
## Environments
* Framework name: -
* Framework version:-
* Moveable Component version: 0.27.2
* Testable Address(optional):

## Description
The cursors on the direction handle are too big / zoomed in FIREFOX.
JsFiddle as below.
https://jsfiddle.net/fjxz7pkc/

https://user-images.githubusercontent.com/5429119/148758411-7a180267-4ff8-4694-8c15-1469381156a9.mov

**Comment by Elewyth** [comment]
I noticed this seems to happen because react-moveable sets a custom SVG as the cursor image on hover. Not sure if this happens in other packages, the SVG Cursor seems to be specifically in the react-moveable: https://github.com/daybrush/moveable/blob/bf5be1752a520f0d9749b35a6e6a87a4c58b3188/packages/react-moveable/src/react-moveable/consts.ts#L5

Why this is done, I don't understand, but I imagine by using some CSS with `!important` the cursor can probably be reset back to the firefox default (e.g. using `cursor: ns-resize !important`).

**Comment by daybrush** [comment]
@adilmas13 @Elewyth 



* `moveable` 0.28.0
* `react-moveable` 0.31.1
* `preact-moveable` 0.30.0
* `ngx-moveable` 0.24.0
* `svelte-moveable` 0.18.0
* `lit-moveable` 0.5.0
* `vue-moveable` 2.0.0-beta.6
* `vue3-moveable` 0.3.0

moveable's new version is released.
Check it again.

**Comment by Elewyth** [comment]
I can confirm the cursor looks normal-sized now in Firefox for me, thanks :)
