### ISSUE TITLE
1px error with keepRatio

### ISSUE THREAD

**Issue by GrigoreAlexandru** [daybrush/moveable#634]
In the storybook, we resize the target to a arbitrary size:
![image](https://user-images.githubusercontent.com/25285065/162735591-bd585c0f-385a-437c-88ec-8470e6568877.png)
lock the aspect ratio, change the width and calculate the next height:
![image](https://user-images.githubusercontent.com/25285065/162735715-77bc3f72-b055-4c6b-8d1f-94bface52a9d.png)
With the new 232px width, we should have a height of  182px
![image](https://user-images.githubusercontent.com/25285065/162735762-8014af8e-b5de-46cc-9bf4-5140595b7146.png)
But what happens is we get a height of 183px. I believe this is because of some rounding somewhere. But 182.xxx px is still 182px on the screen, so there should be no rounding when dealing with width/height and instead discard the decimals with Math.trunc().

**Comment by daybrush** [comment]
@GrigoreAlexandru 

I'm sorry. However, the browser recognizes it as rounding.

I'm thinking about not using rounding right now.

**Comment by daybrush** [comment]
@GrigoreAlexandru 

* `moveable` 0.29.1
* `react-moveable` 0.32.1
* `preact-moveable` 0.31.1
* `ngx-moveable` 0.25.1
* `svelte-moveable` 0.19.1
* `lit-moveable` 0.6.1
* `vue-moveable` 2.0.0-beta.8
* `vue3-moveable` 0.4.1

moveable's new version is released.

use resizeFormat instead of throttleResize.

```js
throttleResize={0}
resizeFormat={size => ([Math.trunc(size[0]), Math.trunc(size[1])])}
```
